# Generated by Django 4.0.6 on 2022-08-10 03:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_alter_mensaje_fecha_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_mensaje',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
